# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    labels:
      - "frontend"
    allow:
      - dependency-name: "@squidcloud/react"
      - dependency-name: "@squidcloud/client"

  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "daily"
    labels:
      - "backend"
    allow:
      - dependency-name: "@squidcloud/client"
      - dependency-name: "@squidcloud/backend"
      - dependency-name: "@squidcloud/local-backend"
